# Build configuration for https://atom.io/packages/build
cmd: stack build
name: semantic-diff
env:
  PATH: ~/.local/bin:~/Developer/Tools:~/Library/Haskell/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
targets:
  test:
    cmd: stack build :integration-test
    keymap: cmd-u
errorMatch:
- \n(?<file>/[^:]+):(?<line>\d+):((?<col>\d+):)?
