flags: {}
extra-package-dbs: []
packages:
- '.'
- vendor/haskell-tree-sitter
- vendor/haskell-tree-sitter/languages/go
- vendor/haskell-tree-sitter/languages/haskell
- vendor/haskell-tree-sitter/languages/java
- vendor/haskell-tree-sitter/languages/json
- vendor/haskell-tree-sitter/languages/php
- vendor/haskell-tree-sitter/languages/python
- vendor/haskell-tree-sitter/languages/ruby
- vendor/haskell-tree-sitter/languages/typescript
- vendor/hspec-expectations-pretty-diff
- vendor/proto3-suite
- vendor/proto3-wire

extra-deps:
- generic-monoid-0.1.0.0@sha256:00d1a7b7ff0890a3e3cba4032be24fe377c26e5e45d73afcacd42c98abb3b7e3,818
- http-client-0.6.4@sha256:a74b417345857d4250bdb6d4ac7fd4a89fd2ad8efab3164c1a2b843398d5c13a,5320
- semilattices-0.0.0.3@sha256:215d40aa231ed1786211809a5f4b7768a708a8ac1625507b9d5ddb4929323a8e,2108
- fused-effects-0.4.0.0@sha256:e9744131a9140968147389e7bbb7e4b448034af5829a27fffdbefb5688daefa3,4257
- fused-effects-exceptions-0.1.1.0@sha256:1dd2acfe9e2bd7d2c0422f1a9368c7be0fc8b59c3f0a5952a54dd273cb20f3d4,1103
- git: git@github.com:patrickt/fastsum.git
  commit: 8e90566ff3b4ac3991040f80c5961b7da4f66631

resolver: lts-13.13