name: Bazel CI

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: Bazel
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      if: github.event.action == 'opened' || github.event.action == 'synchronize' || github.event.ref == 'refs/heads/master'

    - uses: actions/cache@v1
      id: cache-cabal
      name: Cache Bazel artifacts
      with:
        path: .bazel-cache
        key: ${{ runner.os }}-bazel-${{ hashFiles('semantic-*/**/*.hs') }}-${{ hashFiles('**/*.bazel') }}-${{ hashFiles('**/*.bzl') }}
        restore-keys: |
          ${{ runner.os }}-bazel-${{ hashFiles('semantic-*/**/*.hs') }}-${{ hashFiles('**/*.bazel') }}-
          ${{ runner.os }}-bazel-${{ hashFiles('semantic-*/**/*.hs') }}-
          ${{ runner.os }}-bazel-

    - name: Build & test
      run: |
        bazel build --config=ci //semantic:all
        bazel test --config=ci --test_tag_filters=language-test //...
        bazel test //semantic-source //semantic:spec
